// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLibrary.Web.Data;

#nullable disable

namespace MiniLibrary.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618142559_FinalizeLibraryModel")]
    partial class FinalizeLibraryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniLibrary.Web.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gilbert Strang",
                            AvailableCopies = 10,
                            BookCode = "MATH-001",
                            CategoryId = 1,
                            RentalPrice = 15000m,
                            Title = "Advanced Linear Algebra"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sheldon Ross",
                            AvailableCopies = 2,
                            BookCode = "MATH-002",
                            CategoryId = 1,
                            RentalPrice = 12000m,
                            Title = "Applied Probability"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ian Goodfellow",
                            AvailableCopies = 5,
                            BookCode = "CS-001",
                            CategoryId = 2,
                            RentalPrice = 25000m,
                            Title = "Deep Learning Overview"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.BorrowDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowTicketId")
                        .HasColumnType("int");

                    b.Property<decimal>("DepositPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowTicketId");

                    b.ToTable("BorrowDetails");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.BorrowTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.ToTable("BorrowTickets");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Borrowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "studentA@vnu-hcm.edu.vn",
                            Name = "Nguyen Van A"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Applied Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.Book", b =>
                {
                    b.HasOne("MiniLibrary.Web.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.BorrowDetail", b =>
                {
                    b.HasOne("MiniLibrary.Web.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLibrary.Web.Models.BorrowTicket", "BorrowTicket")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BorrowTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowTicket");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.BorrowTicket", b =>
                {
                    b.HasOne("MiniLibrary.Web.Models.Borrower", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.BorrowTicket", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("MiniLibrary.Web.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
